services:
  mysql:
    container_name: seo_mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "seomasterr1999AS"
      MYSQL_DATABASE: seo_db
      MYSQL_USER: seo_user
      MYSQL_PASSWORD: "seomasterr1999AS"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - seonet

  backend:
    container_name: seo_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mysql
    networks:
      - seonet

  frontend:
    container_name: seo_frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    restart: always
    networks:
      - seonet

volumes:
  mysql_data:

networks:
  seonet:
    driver: bridge
