version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
    expose:
      - "80"
    restart: always
