version: '3.8'

services:
  backend:
    container_name: seo_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: always
    networks:
      - seonet

  frontend:
    container_name: seo_frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    restart: always
    networks:
      - seonet

networks:
  seonet:
    driver: bridge
